services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    nativeEnvironments:
      - ffmpeg